name: Python App

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      - name : install requriments.txt
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [-f requirements.txt]; then pip install -r requirements.txt;
      - name: lint with flake
        run: |
        flake8 . --count --select=E2,E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zore --max-complexity=10 --max-line-length=127 --statistics